### ISSUE TITLE
1.9 not working on latest Spigot 1.8.8

### ISSUE THREAD

**Issue by helptiger** [Howaner/FakeMobs#8]
10:49:44 ERROR]: Error occurred while enabling FakeMobs v1.8.9-Rewi (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/Packet
	at de.howaner.FakeMobs.FakeMobsPlugin.loadMobsFile(FakeMobsPlugin.java:274) ~[?:?]
	at de.howaner.FakeMobs.FakeMobsPlugin.onEnable(FakeMobsPlugin.java:58) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_10]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_10]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_10]
	... 13 more

**Comment by PhanaticD** [comment]
commenting so i get notified if this is ever updated for 1.9
